/// <reference path="../pb_data/types.d.ts" />
migrate(
  (db) => {
    const snapshot = [
      {
        id: "_pb_users_auth_",
        created: "2026-07-20 01:24:54.826Z",
        updated: "2026-07-26 14:46:25.852Z",
        name: "users",
        type: "auth",
        system: false,
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        schema: [
          {
            system: false,
            id: "users_name",
            name: "name",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "users_avatar",
            name: "avatar",
            type: "file",
            required: false,
            presentable: false,
            unique: false,
            options: {
              mimeTypes: [
                "image/jpeg",
                "image/png",
                "image/svg+xml",
                "image/gif",
                "image/webp",
              ],
              thumbs: null,
              maxSelect: 1,
              maxSize: 5242880,
              protected: false,
            },
          },
          {
            system: false,
            id: "userrolefld",
            name: "role",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["admin", "operator"],
            },
          },
          {
            system: false,
            id: "useractivefl",
            name: "active",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [],
        listRule: "id = @request.auth.id",
        viewRule: "id = @request.auth.id",
        createRule: "",
        updateRule: "id = @request.auth.id",
        deleteRule: "id = @request.auth.id",
        options: {
          allowEmailAuth: true,
          allowOAuth2Auth: true,
          allowUsernameAuth: true,
          exceptEmailDomains: null,
          manageRule: null,
          minPasswordLength: 8,
          onlyEmailDomains: null,
          onlyVerified: false,
          requireEmail: false,
        },
      },
      {
        id: "somoim_members00",
        created: "2026-07-20 01:24:54.846Z",
        updated: "2026-07-26 14:46:25.854Z",
        name: "members",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "y560cobl",
            name: "name",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "nwu4imk2",
            name: "nickname",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "mishfr4k",
            name: "gender",
            type: "select",
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["M", "F"],
            },
          },
          {
            system: false,
            id: "seiexuxz",
            name: "phone",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 255,
              pattern: "",
            },
          },
          {
            system: false,
            id: "rw0yeazq",
            name: "rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "hy6c4yhk",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["active", "inactive"],
            },
          },
          {
            system: false,
            id: "8axwlswe",
            name: "memo",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "2ekxzp4x",
            name: "joined_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "mbrphonehash",
            name: "phone_hash",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 64,
              pattern: "",
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_members_identity` ON `members` (`name`, `phone_hash`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_rank_set0",
        created: "2026-07-20 01:24:54.847Z",
        updated: "2026-07-26 14:46:25.859Z",
        name: "rank_settings",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "ylbz8cx7",
            name: "min_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "kjelgiit",
            name: "max_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "cvbo8msq",
            name: "promotion_threshold",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "evhfjxzu",
            name: "demotion_threshold",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "defmemberrank",
            name: "default_member_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "defguestrank",
            name: "default_guest_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
        ],
        indexes: [],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_events00",
        created: "2026-07-20 01:24:54.852Z",
        updated: "2026-07-27 06:45:26.981Z",
        name: "events",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "ghoxsfea",
            name: "title",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 150,
              pattern: "",
            },
          },
          {
            system: false,
            id: "it7jp7ye",
            name: "event_date",
            type: "date",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "0szmu1x1",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["draft", "active", "completed", "archived"],
            },
          },
          {
            system: false,
            id: "8gqcq7w7",
            name: "notice",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 3000,
              pattern: "",
            },
          },
          {
            system: false,
            id: "bncwqwxd",
            name: "public_token_hash",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 128,
              pattern: "",
            },
          },
          {
            system: false,
            id: "e6rgsffb",
            name: "public_access_enabled",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "6nrzzzcd",
            name: "public_expires_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "03mahl4r",
            name: "created_by",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["email"],
            },
          },
          {
            system: false,
            id: "ushp2fi1",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "pubtokencrypt",
            name: "public_token_encrypted",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 1000,
              pattern: "",
            },
          },
          {
            system: false,
            id: "eventregstatus",
            name: "participation_status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["open", "closed"],
            },
          },
          {
            system: false,
            id: "eventregclosed",
            name: "participation_closed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_events_event_date` ON `events` (`event_date`)",
          "CREATE INDEX `idx_events_status` ON `events` (`status`)",
          "CREATE UNIQUE INDEX `idx_events_public_token_hash` ON `events` (`public_token_hash`) WHERE `public_token_hash` != ''",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_evtparts",
        created: "2026-07-20 01:24:54.854Z",
        updated: "2026-07-26 14:46:25.864Z",
        name: "event_participants",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "hhzk6qot",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "gcs4xpfi",
            name: "participant_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["member", "guest"],
            },
          },
          {
            system: false,
            id: "zis1ssnq",
            name: "member",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_members00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["nickname", "name"],
            },
          },
          {
            system: false,
            id: "r01uv6un",
            name: "guest_name",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "o1rtsrzs",
            name: "display_name",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "opg5hma5",
            name: "rank_snapshot",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "d91myz0u",
            name: "game_participation_status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["undecided", "playing", "not_playing"],
            },
          },
          {
            system: false,
            id: "et9hnpci",
            name: "participation_token_hash",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 128,
              pattern: "",
            },
          },
          {
            system: false,
            id: "tqsqgema",
            name: "participation_responded_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "8tgospli",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_event_participants_event` ON `event_participants` (`event`)",
          "CREATE INDEX `idx_event_participants_member` ON `event_participants` (`member`)",
          "CREATE INDEX `idx_event_participants_game_status` ON `event_participants` (`game_participation_status`)",
          "CREATE UNIQUE INDEX `idx_event_participants_event_member` ON `event_participants` (`event`, `member`) WHERE `member` != ''",
          "CREATE UNIQUE INDEX `idx_event_participants_token` ON `event_participants` (`participation_token_hash`) WHERE `participation_token_hash` != ''",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_gameset0",
        created: "2026-07-20 23:42:02.311Z",
        updated: "2026-07-28 08:24:42.051Z",
        name: "event_game_settings",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "t0985cxm",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "okzgyfoc",
            name: "competition_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["team_league", "individual_singles"],
            },
          },
          {
            system: false,
            id: "jexs7wde",
            name: "team_size",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "amwrv16y",
            name: "auto_team_balance",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "gckhq9xu",
            name: "individual_best_of",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "xju7ngze",
            name: "individual_counts_for_ranking",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "tz32lrda",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["draft", "confirmed"],
            },
          },
          {
            system: false,
            id: "0ux2rfej",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "gamesettablecnt",
            name: "individual_table_count",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: 30,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "gamesetopstate",
            name: "operation_status",
            type: "select",
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["not_started", "in_progress", "completed"],
            },
          },
        ],
        indexes: [
          "CREATE UNIQUE INDEX `idx_event_game_settings_event` ON `event_game_settings` (`event`)",
          "CREATE INDEX `idx_event_game_settings_type` ON `event_game_settings` (`competition_type`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_gamefmt0",
        created: "2026-07-20 23:42:02.324Z",
        updated: "2026-07-26 14:46:25.867Z",
        name: "event_match_formats",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "yuenkbp8",
            name: "game_setting",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_gameset0",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["competition_type"],
            },
          },
          {
            system: false,
            id: "qxucujjj",
            name: "sequence",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "sx4uiqdp",
            name: "match_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["singles", "doubles"],
            },
          },
          {
            system: false,
            id: "6x3axqp1",
            name: "best_of",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "jvw5qbrh",
            name: "counts_for_ranking",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [
          "CREATE INDEX `idx_event_match_formats_setting` ON `event_match_formats` (`game_setting`)",
          "CREATE UNIQUE INDEX `idx_event_match_formats_sequence` ON `event_match_formats` (`game_setting`, `sequence`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_teamform",
        created: "2026-07-21 13:16:49.734Z",
        updated: "2026-07-26 14:46:25.869Z",
        name: "team_formations",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "formationevent",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "formgamesetting",
            name: "game_setting",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_gameset0",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["competition_type"],
            },
          },
          {
            system: false,
            id: "formationmethod",
            name: "method",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["balanced", "random"],
            },
          },
          {
            system: false,
            id: "formationstatus",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["draft", "confirmed"],
            },
          },
          {
            system: false,
            id: "qualityscorefld",
            name: "quality_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: 100,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "formationversn",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE UNIQUE INDEX `idx_team_formations_game_setting` ON `team_formations` (`game_setting`)",
          "CREATE INDEX `idx_team_formations_event` ON `team_formations` (`event`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_teams000",
        created: "2026-07-21 13:16:49.747Z",
        updated: "2026-07-26 14:46:25.870Z",
        name: "teams",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "teamformation",
            name: "formation",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teamform",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["status"],
            },
          },
          {
            system: false,
            id: "teamevent",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "teamname",
            name: "name",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 30,
              pattern: "",
            },
          },
          {
            system: false,
            id: "teamsortorder",
            name: "sort_order",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "teamavgrank",
            name: "average_rank",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: "teamversion",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_teams_event` ON `teams` (`event`)",
          "CREATE INDEX `idx_teams_formation` ON `teams` (`formation`)",
          "CREATE UNIQUE INDEX `idx_teams_name` ON `teams` (`formation`, `name`)",
          "CREATE UNIQUE INDEX `idx_teams_sort_order` ON `teams` (`formation`, `sort_order`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_teammemb",
        created: "2026-07-21 13:16:49.748Z",
        updated: "2026-07-26 14:46:25.875Z",
        name: "team_members",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "memberformation",
            name: "formation",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teamform",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["status"],
            },
          },
          {
            system: false,
            id: "memberevent",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "memberteam",
            name: "team",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teams000",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["name"],
            },
          },
          {
            system: false,
            id: "memberparticpt",
            name: "participant",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "memberranksnap",
            name: "rank_snapshot",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "membersortorder",
            name: "sort_order",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_team_members_event` ON `team_members` (`event`)",
          "CREATE INDEX `idx_team_members_team` ON `team_members` (`team`)",
          "CREATE UNIQUE INDEX `idx_team_members_participant` ON `team_members` (`formation`, `participant`)",
          "CREATE UNIQUE INDEX `idx_team_members_sort_order` ON `team_members` (`team`, `sort_order`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        updateRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        deleteRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        options: {},
      },
      {
        id: "somoim_tmatch00",
        created: "2026-07-22 03:57:31.850Z",
        updated: "2026-07-27 07:24:40.751Z",
        name: "team_matches",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "26ao7idt",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "w5i8x046",
            name: "game_setting",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_gameset0",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["competition_type"],
            },
          },
          {
            system: false,
            id: "whn3rs2m",
            name: "formation",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teamform",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["status"],
            },
          },
          {
            system: false,
            id: "z9dvhenb",
            name: "home_team",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teams000",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["name"],
            },
          },
          {
            system: false,
            id: "4ca5crr9",
            name: "away_team",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teams000",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["name"],
            },
          },
          {
            system: false,
            id: "wwpihdmh",
            name: "pair_key",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 3,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "5beizozb",
            name: "round",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "8kqko8gq",
            name: "sort_order",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "oetmaptr",
            name: "format_snapshot",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 2,
              max: 10000,
              pattern: "",
            },
          },
          {
            system: false,
            id: "9ntjrguc",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: [
                "scheduled",
                "ready",
                "in_progress",
                "completed",
                "cancelled",
              ],
            },
          },
          {
            system: false,
            id: "drfnxkk2",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "teammatchstart",
            name: "started_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "teammatchdone",
            name: "completed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_team_matches_event` ON `team_matches` (`event`)",
          "CREATE INDEX `idx_team_matches_formation` ON `team_matches` (`formation`)",
          "CREATE UNIQUE INDEX `idx_team_matches_pair` ON `team_matches` (`formation`, `pair_key`)",
          "CREATE UNIQUE INDEX `idx_team_matches_order` ON `team_matches` (`formation`, `sort_order`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_mgames00",
        created: "2026-07-22 03:57:31.862Z",
        updated: "2026-07-27 07:29:08.736Z",
        name: "match_games",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "lpou6lg0",
            name: "team_match",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_tmatch00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "qsmdufcm",
            name: "sequence",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "sxmeigub",
            name: "match_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["singles", "doubles"],
            },
          },
          {
            system: false,
            id: "abyll6yo",
            name: "best_of",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "dxyjxziv",
            name: "counts_for_ranking",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "6qyziyj0",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["scheduled", "in_progress", "completed", "cancelled"],
            },
          },
          {
            system: false,
            id: "ttm1lgwb",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "mgresultstatus",
            name: "result_status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["pending", "disputed", "confirmed"],
            },
          },
          {
            system: false,
            id: "mghomescorefld",
            name: "home_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "mgawayscorefld",
            name: "away_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "mgwinnerfield",
            name: "winner_side",
            type: "select",
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["home", "away"],
            },
          },
          {
            system: false,
            id: "mgconfirmatfld",
            name: "result_confirmed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_match_games_match` ON `match_games` (`team_match`)",
          "CREATE UNIQUE INDEX `idx_match_games_sequence` ON `match_games` (`team_match`, `sequence`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_lineups0",
        created: "2026-07-22 03:57:31.864Z",
        updated: "2026-07-26 14:46:25.879Z",
        name: "team_match_lineups",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "4yuxputw",
            name: "team_match",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_tmatch00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "u7pjspvo",
            name: "team",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_teams000",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["name"],
            },
          },
          {
            system: false,
            id: "c8srmfyr",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["draft", "confirmed"],
            },
          },
          {
            system: false,
            id: "btfyecjb",
            name: "confirmed_by",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "wsi8vfxt",
            name: "confirmed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "scrlp590",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_lineups_match` ON `team_match_lineups` (`team_match`)",
          "CREATE INDEX `idx_lineups_team` ON `team_match_lineups` (`team`)",
          "CREATE UNIQUE INDEX `idx_lineups_match_team` ON `team_match_lineups` (`team_match`, `team`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_players0",
        created: "2026-07-22 03:57:31.865Z",
        updated: "2026-07-26 14:46:25.881Z",
        name: "match_game_players",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "h9kbfipy",
            name: "lineup",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_lineups0",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["status"],
            },
          },
          {
            system: false,
            id: "cnshzywt",
            name: "match_game",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_mgames00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["sequence", "match_type"],
            },
          },
          {
            system: false,
            id: "a88ghtpm",
            name: "participant",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "r2nvcdxe",
            name: "position",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 2,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_players_lineup` ON `match_game_players` (`lineup`)",
          "CREATE INDEX `idx_players_game` ON `match_game_players` (`match_game`)",
          "CREATE UNIQUE INDEX `idx_players_position` ON `match_game_players` (`lineup`, `match_game`, `position`)",
          "CREATE UNIQUE INDEX `idx_players_participant` ON `match_game_players` (`lineup`, `match_game`, `participant`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_imatch00",
        created: "2026-07-23 00:22:32.388Z",
        updated: "2026-07-28 08:24:42.080Z",
        name: "individual_matches",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "gjbgi61o",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "9tpjlpvd",
            name: "game_setting",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_gameset0",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["competition_type"],
            },
          },
          {
            system: false,
            id: "ooxffiix",
            name: "home_participant",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "0wgtsq3e",
            name: "away_participant",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "tclmkary",
            name: "pair_key",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 3,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "z1ulpuq2",
            name: "round",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "yhpvkt6c",
            name: "sort_order",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "hnxbdxa1",
            name: "best_of",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "iuwgkz9g",
            name: "counts_for_ranking",
            type: "bool",
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "glgaewcq",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["scheduled", "in_progress", "completed", "cancelled"],
            },
          },
          {
            system: false,
            id: "2rzdwekm",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "indmatchstart",
            name: "started_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "indmatchdone",
            name: "completed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "imresultstatus",
            name: "result_status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["pending", "disputed", "confirmed"],
            },
          },
          {
            system: false,
            id: "imhomescorefld",
            name: "home_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "imawayscorefld",
            name: "away_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "imwinnerfield",
            name: "winner_side",
            type: "select",
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["home", "away"],
            },
          },
          {
            system: false,
            id: "imconfirmatfld",
            name: "result_confirmed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "indmatchtable",
            name: "table_number",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: 30,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_indiv_matches_event` ON `individual_matches` (`event`)",
          "CREATE INDEX `idx_indiv_matches_setting` ON `individual_matches` (`game_setting`)",
          "CREATE UNIQUE INDEX `idx_indiv_matches_pair` ON `individual_matches` (`game_setting`, `pair_key`)",
          "CREATE UNIQUE INDEX `idx_indiv_matches_order` ON `individual_matches` (`game_setting`, `sort_order`)",
        ],
        listRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        viewRule:
          "@request.auth.id != '' && @request.auth.role = 'admin' && @request.auth.active = true",
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_resub00",
        created: "2026-07-27 07:29:08.739Z",
        updated: "2026-07-27 07:29:08.739Z",
        name: "match_result_submissions",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "resulteventfld",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "resulttypefld",
            name: "target_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["team_game", "individual_match"],
            },
          },
          {
            system: false,
            id: "resultgamefld",
            name: "match_game",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_mgames00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["sequence", "match_type"],
            },
          },
          {
            system: false,
            id: "resultindivfld",
            name: "individual_match",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_imatch00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "resultsidefld",
            name: "submitted_side",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["home", "away"],
            },
          },
          {
            system: false,
            id: "resultsubmitby",
            name: "submitted_by",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "resulthomescor",
            name: "home_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "resultawayscor",
            name: "away_score",
            type: "number",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: 0,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "resultversion",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_result_submissions_event` ON `match_result_submissions` (`event`)",
          "CREATE INDEX `idx_result_submissions_submitter` ON `match_result_submissions` (`submitted_by`)",
          "CREATE INDEX `idx_result_submissions_game` ON `match_result_submissions` (`match_game`)",
          "CREATE INDEX `idx_result_submissions_individual` ON `match_result_submissions` (`individual_match`)",
          "CREATE UNIQUE INDEX `idx_result_team_side` ON `match_result_submissions` (`match_game`, `submitted_side`) WHERE `match_game` != ''",
          "CREATE UNIQUE INDEX `idx_result_individual_side` ON `match_result_submissions` (`individual_match`, `submitted_side`) WHERE `individual_match` != ''",
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_reshist0",
        created: "2026-07-28 05:09:11.636Z",
        updated: "2026-07-28 05:09:11.636Z",
        name: "match_result_history",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "hist_event_fld",
            name: "event",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_events00",
              cascadeDelete: true,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["title"],
            },
          },
          {
            system: false,
            id: "hist_type_fld",
            name: "target_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["team_match", "team_game", "individual_match"],
            },
          },
          {
            system: false,
            id: "hist_team_fld",
            name: "team_match",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_tmatch00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "hist_game_fld",
            name: "match_game",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_mgames00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["sequence", "match_type"],
            },
          },
          {
            system: false,
            id: "hist_indiv_fld",
            name: "individual_match",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_imatch00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "hist_action_fld",
            name: "action",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: [
                "submitted",
                "updated",
                "confirmed",
                "disputed",
                "cancelled",
              ],
            },
          },
          {
            system: false,
            id: "hist_requestid",
            name: "request_id",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 100,
              pattern: "",
            },
          },
          {
            system: false,
            id: "hist_actor_fld",
            name: "actor_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["participant", "admin", "system"],
            },
          },
          {
            system: false,
            id: "hist_part_fld",
            name: "actor_participant",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_evtparts",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["display_name"],
            },
          },
          {
            system: false,
            id: "hist_admin_fld",
            name: "actor_admin",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["email"],
            },
          },
          {
            system: false,
            id: "hist_name_fld",
            name: "actor_name",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 200,
              pattern: "",
            },
          },
          {
            system: false,
            id: "hist_side_fld",
            name: "submitted_side",
            type: "select",
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["home", "away"],
            },
          },
          {
            system: false,
            id: "hist_beforefld",
            name: "before_data",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 10000,
              pattern: "",
            },
          },
          {
            system: false,
            id: "hist_after_fld",
            name: "after_data",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 10000,
              pattern: "",
            },
          },
          {
            system: false,
            id: "hist_reason_fld",
            name: "reason",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 500,
              pattern: "",
            },
          },
        ],
        indexes: [
          "CREATE UNIQUE INDEX `idx_result_history_request` ON `match_result_history` (`request_id`)",
          "CREATE INDEX `idx_result_history_event` ON `match_result_history` (`event`)",
          "CREATE INDEX `idx_result_history_team` ON `match_result_history` (`team_match`)",
          "CREATE INDEX `idx_result_history_game` ON `match_result_history` (`match_game`)",
          "CREATE INDEX `idx_result_history_individual` ON `match_result_history` (`individual_match`)",
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_rankcand",
        created: "2026-07-29 04:35:45.554Z",
        updated: "2026-07-29 04:35:45.554Z",
        name: "ranking_adjustment_candidates",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "rankcandmember",
            name: "member",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_members00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["nickname", "rank"],
            },
          },
          {
            system: false,
            id: "rankcanddirect",
            name: "direction",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["promotion", "demotion"],
            },
          },
          {
            system: false,
            id: "rankcandcurrent",
            name: "current_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankcandpropose",
            name: "proposed_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankcandstreak",
            name: "streak_count",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankcandthresh",
            name: "threshold",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankcandstatus",
            name: "status",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["pending", "approved", "rejected", "obsolete"],
            },
          },
          {
            system: false,
            id: "rankcandsource",
            name: "source_type",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["team_game", "individual_match"],
            },
          },
          {
            system: false,
            id: "rankcandgame",
            name: "match_game",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_mgames00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["sequence", "match_type"],
            },
          },
          {
            system: false,
            id: "rankcandindiv",
            name: "individual_match",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_imatch00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["round", "sort_order"],
            },
          },
          {
            system: false,
            id: "rankcandbasis",
            name: "basis_key",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 200,
              pattern: "",
            },
          },
          {
            system: false,
            id: "rankcandcalcat",
            name: "calculated_at",
            type: "date",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "rankcandreview",
            name: "reviewed_by",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["email"],
            },
          },
          {
            system: false,
            id: "rankcandrevdate",
            name: "reviewed_at",
            type: "date",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "rankcandnote",
            name: "review_note",
            type: "text",
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: 500,
              pattern: "",
            },
          },
          {
            system: false,
            id: "rankcandversion",
            name: "version",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: null,
              noDecimal: true,
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_rank_candidates_member` ON `ranking_adjustment_candidates` (`member`)",
          "CREATE INDEX `idx_rank_candidates_status` ON `ranking_adjustment_candidates` (`status`)",
          "CREATE UNIQUE INDEX `idx_rank_candidates_basis` ON `ranking_adjustment_candidates` (`member`, `basis_key`)",
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "somoim_rankhist",
        created: "2026-07-29 04:35:45.566Z",
        updated: "2026-07-29 04:35:45.566Z",
        name: "member_rank_history",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "rankhistmember",
            name: "member",
            type: "relation",
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_members00",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["nickname", "rank"],
            },
          },
          {
            system: false,
            id: "rankhistcand",
            name: "candidate",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "somoim_rankcand",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["direction", "status"],
            },
          },
          {
            system: false,
            id: "rankhistprev",
            name: "previous_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankhistnext",
            name: "new_rank",
            type: "number",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 99,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: "rankhistdirect",
            name: "direction",
            type: "select",
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["promotion", "demotion", "manual"],
            },
          },
          {
            system: false,
            id: "rankhistreason",
            name: "reason",
            type: "text",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: 1,
              max: 500,
              pattern: "",
            },
          },
          {
            system: false,
            id: "rankhistadmin",
            name: "approved_by",
            type: "relation",
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: ["email"],
            },
          },
          {
            system: false,
            id: "rankhisteffect",
            name: "effective_at",
            type: "date",
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        indexes: [
          "CREATE INDEX `idx_rank_history_member` ON `member_rank_history` (`member`)",
          "CREATE INDEX `idx_rank_history_effective` ON `member_rank_history` (`effective_at`)",
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
    ];

    const collections = snapshot.map((item) => new Collection(item));

    /*
     * users Auth Collection의 일반 Record API를 전부 잠급니다.
     * 로그인과 토큰 갱신은 Auth API이므로 계속 사용할 수 있습니다.
     */
    const usersCollection = collections.find(
      (collection) => collection.name === "users",
    );

    if (!usersCollection) {
      throw new Error("users 컬렉션을 찾을 수 없습니다.");
    }

    usersCollection.listRule = null;
    usersCollection.viewRule = null;
    usersCollection.createRule = null;
    usersCollection.updateRule = null;
    usersCollection.deleteRule = null;

    const dao = new Dao(db);

    /*
     * 현재 최종 컬렉션 구조를 DB에 적용합니다.
     * true이므로 스냅샷에 없는 사용자 컬렉션과 필드는 제거됩니다.
     */
    dao.importCollections(collections, true, null);

    /*
     * 컬렉션 스냅샷에는 레코드가 포함되지 않으므로
     * 최초 운영에 필요한 기본 부수 설정을 직접 생성합니다.
     */
    const rankSettingsCollection =
      dao.findCollectionByNameOrId("rank_settings");

    const existingRankSettings = dao.findRecordsByFilter(
      "rank_settings",
      "id != ''",
      "created",
      1,
      0,
    );

    if (existingRankSettings.length === 0) {
      const rankSettingsRecord = new Record(rankSettingsCollection);

      rankSettingsRecord.set("min_rank", 1);
      rankSettingsRecord.set("max_rank", 8);
      rankSettingsRecord.set("default_member_rank", 8);
      rankSettingsRecord.set("default_guest_rank", 8);
      rankSettingsRecord.set("promotion_threshold", 3);
      rankSettingsRecord.set("demotion_threshold", 4);

      dao.saveRecord(rankSettingsRecord);
    }

    /*
     * 요청 로그 DB가 반복 손상됐던 개발 환경과 동일하게
     * PocketBase 기본 요청 로그 저장을 비활성화합니다.
     *
     * 경기 결과 이력과 부수 변경 이력은 data.db에 계속 저장됩니다.
     */
    const settings = dao.findSettings();

    settings.logs.maxDays = 0;
    settings.logs.logIp = false;

    dao.saveSettings(settings);
  },
  (db) => {
    /*
     * 최초 스키마 마이그레이션은 전체 컬렉션을 생성하므로
     * 운영 데이터 보호를 위해 자동 롤백하지 않습니다.
     */
    return null;
  },
);
